services:
  mongodb:
    image: mongo
    container_name: desafiodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: "desafios"
    volumes:
      - ./data:/data/desafiodb
volumes:
  mongodb_data: